### ISSUE TITLE
Frontend error using helm chart to deploy

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-frontend#9] opened 2020-10-21 13:45 UTC
Illuminate\Database\QueryException
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "k_reports" does not exist LINE 1: select count(distinct "uid") as aggregate from "k_reports" ^ (SQL: select count(distinct "uid") as aggregate from "k_reports")

Illuminate\Database\Connection::runQueryCallback
vendor/laravel/framework/src/Illuminate/Database/Connection.php:671

I shared also here:
https://flareapp.io/share/VP6K1V07

It happens once I port forward and open the Frontend. Have never worked. I hope the details provided help!

**Comment by mms-gianni** [comment] 2020-11-05 07:12
Thank you for opening my very first issue here on github :D 

Did you ran the migrations inside your container? 
```
php artisan migrate
```

There is a refactored version of the helm chart on going which are addressing this issue with a initContainer. 

https://github.com/klustair/klustair-helm/blob/refactoring/templates/frontend-deployment.yaml#L30

**Comment by hugodopradofernandes** [comment] 2020-11-05 12:08
I'll try that soon and post here the result :)

**Comment by hugodopradofernandes** [comment] 2020-11-06 06:15
New error using the Helm package klustair-0.1.0.tgz (Refactoring)

_$ helm install klustair ./klustair-0.1.0.tgz -n klustair
Error: template: klustair/templates/cronjob.yaml:35:33: executing "klustair/templates/cronjob.yaml" at <.Values.postpostgresqlgres.postgresqlUsername>: nil pointer evaluating interface {}.postgresqlUsername_

Line 35 of cronjob.yaml has a wrong string:

                value: {{ .Values.postpostgresqlgres.postgresqlUsername | quote}}

Should be:

                value: {{ .Values.postgresql.postgresqlUsername | quote}}


But even fixing that I was facing a lot of yaml identation issues on helm also from cronjob.yaml . I tried to fix it, without luck.

**Comment by mms-gianni** [comment] 2020-11-07 00:03
You are right. This is a copy/paste error I made. Sorry. 
I just fixed it in the refactoring branch.

I cant reproduce this error currently.
`
$ helm template .  
`

rendered the template as expected.

**Comment by mms-gianni** [comment] 2020-11-09 09:38
I found several intend errors in the cronjob.yaml. They are fixed now in the new "main" branch.

**Comment by hugodopradofernandes** [comment] 2020-11-09 13:02
I was now able to sucessfull deploy the chart and the frontend is working. I'm now going to install the anchore engine to test the full tool, but we can close this issue for now
Thanks!

**Comment by mms-gianni** [comment] 2020-11-10 08:15
you're welcome 

Let me know if you have any other issues. I actually make a lot of changes in every 3 projects. 

BTW: A Anchore installation is not necessary anymore if you scan your images with the included trivy scanner.

**Closed by mms-gianni** 2020-11-10 08:15 UTC
